language: python

python:
  - "3.4"
  - "3.5"
  - "3.6-dev"

os:
  - linux

# command to install dependencies
install:
  - pip install requests prettytable pytest pytest-catchlog codecov pytest-cov
  - pip install -e .

env:
 - PYTHON_TEST=1

# command to run tests
script:
  - py.test --cov=./


after_success:
  - bash <(curl -s https://codecov.io/bash)
  - chmod +x tests/travis.sh
  - tests/travis.sh

after_failure:
  - chmod +x tests/travis.sh
  - tests/travis.sh

notifications:
  email:
    recipients:
      - window100@gmail.com
    on_success: always

branches:
  only:
  - master
  - develop
